name: linter-check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: ./app/gradlew checkstyleMain
      - run: ./app/gradlew checkstyleTest
