name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: chmod +x ./app/gradlew

      - run: ./app/gradlew checkstyleMain
      - run: ./app/gradlew checkstyleTest
